package:
  name: expipe-io-neuro
  version: {{ environ.get("GIT_DESCRIBE", "unknown_version")|replace("v", "")|replace("-", "_") }}

source:
  path: .
 
build:
  # noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip
    - numpy
    - quantities

  run:
    - python
    - setuptools
    - pip
    - numpy
    - scipy
    - quantities

test:
  imports:
    - expipe_io_neuro

about:
  home: https://github.com/CINPLA/expipe-io-neuro/
  license: GPLv3
  license_file: LICENSE
