package:
    name: expipe-io-neuro
    version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}
source:
    git_url: ..
build:
    script: python setup.py install
requirements:
    build:
        - python
        - setuptools
        - pip
        - numpy
        - scipy
        - quantities
        - exdir
        - expipe
    run:
        - python
        - setuptools
        - pip
        - numpy
        - scipy
        - quantities
        - exdir
        - expipe
test:
  imports:
      - expipe_io_neuro
about:
    description: 'IO for expipe and neuroscience data'
    dev_url: https://github.com/CINPLA/expipe-io-neuro
    license: GNU GPLv3
    license_family: GPL
    license_file: LICENSE
extra:
    recipe-maintainers:
        - dragly
